defmodule SpazioSolazzo.Repo.Migrations.AddExtraCustomerInfoToBooking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bookings) do
      add :customer_phone, :text, null: false
      add :customer_comment, :text
    end
  end

  def down do
    alter table(:bookings) do
      remove :customer_comment
      remove :customer_phone
    end
  end
end
