defmodule SpazioSolazzo.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bookings) do
      modify :end_time, :time, null: false
      modify :start_time, :time, null: false
      modify :customer_email, :text, null: false
      modify :customer_name, :text, null: false
      modify :date, :date, null: false
    end
  end

  def down do
    alter table(:bookings) do
      modify :date, :date, null: true
      modify :customer_name, :text, null: true
      modify :customer_email, :text, null: true
      modify :start_time, :time, null: true
      modify :end_time, :time, null: true
    end
  end
end
