defmodule SpazioSolazzo.Repo.Migrations.HashVerificationCodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:email_verifications), :code, to: :code_hash
  end

  def down do
    rename table(:email_verifications), :code_hash, to: :code
  end
end
