defmodule SpazioSolazzo.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:time_slot_templates) do
      modify :space_id, :uuid, null: false
      modify :end_time, :time, null: false
      modify :start_time, :time, null: false
      modify :name, :text, null: false
    end

    alter table(:spaces) do
      modify :slug, :text, null: false
      modify :name, :text, null: false
    end

    alter table(:assets) do
      modify :space_id, :uuid, null: false
      modify :name, :text, null: false
    end
  end

  def down do
    alter table(:assets) do
      modify :name, :text, null: true
      modify :space_id, :uuid, null: true
    end

    alter table(:spaces) do
      modify :name, :text, null: true
      modify :slug, :text, null: true
    end

    alter table(:time_slot_templates) do
      modify :name, :text, null: true
      modify :start_time, :time, null: true
      modify :end_time, :time, null: true
      modify :space_id, :uuid, null: true
    end
  end
end
