defmodule SpazioSolazzo.Repo.Migrations.SetPhoneNumberAsNullable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :phone_number, :text, null: true
    end

    alter table(:bookings) do
      modify :customer_phone, :text, null: true
    end
  end

  def down do
    alter table(:bookings) do
      modify :customer_phone, :text, null: false
    end

    alter table(:users) do
      modify :phone_number, :text, null: false
    end
  end
end
