defmodule SpazioSolazzo.Repo.Migrations.SetupResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:time_slot_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :start_time, :time, null: false
      add :end_time, :time, null: false
      add :day_of_week, :text, null: false
      add :space_id, :uuid, null: false
    end

    create table(:spaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:time_slot_templates) do
      modify :space_id,
             references(:spaces,
               column: :id,
               name: "time_slot_templates_space_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:spaces) do
      add :name, :text, null: false
      add :description, :text, null: false
      add :slug, :text, null: false
    end

    create unique_index(:spaces, [:name], name: "spaces_unique_name_index")

    create unique_index(:spaces, [:slug], name: "spaces_unique_slug_index")

    create table(:email_verifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text, null: false
      add :code_hash, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:bookings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :date, :date, null: false
      add :customer_name, :text, null: false
      add :customer_email, :text, null: false
      add :start_time, :time, null: false
      add :end_time, :time, null: false
      add :customer_phone, :text, null: false
      add :customer_comment, :text
      add :state, :text, null: false, default: "reserved"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :asset_id, :uuid
      add :time_slot_template_id, :uuid
    end

    create table(:assets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:bookings) do
      modify :asset_id,
             references(:assets,
               column: :id,
               name: "bookings_asset_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :time_slot_template_id,
             references(:time_slot_templates,
               column: :id,
               name: "bookings_time_slot_template_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:assets) do
      add :name, :text, null: false

      add :space_id,
          references(:spaces,
            column: :id,
            name: "assets_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:assets, [:name, :space_id], name: "assets_unique_name_per_space_index")
  end

  def down do
    drop_if_exists unique_index(:assets, [:name, :space_id],
                     name: "assets_unique_name_per_space_index"
                   )

    drop constraint(:assets, "assets_space_id_fkey")

    alter table(:assets) do
      remove :space_id
      remove :name
    end

    drop constraint(:bookings, "bookings_asset_id_fkey")

    drop constraint(:bookings, "bookings_time_slot_template_id_fkey")

    alter table(:bookings) do
      modify :time_slot_template_id, :uuid
      modify :asset_id, :uuid
    end

    drop table(:assets)

    drop table(:bookings)

    drop table(:email_verifications)

    drop_if_exists unique_index(:spaces, [:slug], name: "spaces_unique_slug_index")

    drop_if_exists unique_index(:spaces, [:name], name: "spaces_unique_name_index")

    alter table(:spaces) do
      remove :slug
      remove :description
      remove :name
    end

    drop constraint(:time_slot_templates, "time_slot_templates_space_id_fkey")

    alter table(:time_slot_templates) do
      modify :space_id, :uuid
    end

    drop table(:spaces)

    drop table(:time_slot_templates)
  end
end
